### ISSUE TITLE
项目跑不起来,项目启动后报错 Cannot find module './src/Application'

### ISSUE THREAD

**Issue by Fantasy9527** [loon-project/loon#17]
git clone 项目之后,npm run dev:start   
会直接报错 Cannot find module './src/Application'

**Comment by vincent178** [comment]
如果你参考例子也是用typescript写的话，你需要先编译ts到js，然后在启动服务器。

**Comment by vincent178** [comment]
请参考 https://github.com/loon-project/loon-boilerplate
启动项目跑 `npm run dev`
