### ISSUE TITLE
按照文档配好项目后，启动之后无法访问站点

### ISSUE THREAD

**Issue by liuhe1989** [loon-project/loon#18]
![image](https://user-images.githubusercontent.com/18466417/33194170-f32d05b2-d108-11e7-80b5-47009b57dbe7.png)

**Comment by liuhe1989** [comment]
启动任何报错信息也没有...

**Comment by liuhe1989** [comment]
tsconfig.json 设置了  "outDir": "./lib"

**Comment by vincent178** [comment]
你的代码给我看一下，从log上看，你一个controller都没有写，自然是没发看到页面的

**Comment by liuhe1989** [comment]
controller 是写了的 我删除掉 tsconfig.json 肿的 "outDir": "./lib" 一切正常

**Comment by vincent178** [comment]
写在什么文件夹下面是可以配置的， 参考https://github.com/loon-project/loon/blob/master/src/server/SettingOptions.ts。

文档有些落后了，现在有`$beforeInit`, `$afterInit`钩子函数。
用钩子函数和ServiceInitializer可以达到同样的效果，但ServiceInitializer是另外一种代码组织方式，通过这个可以把抽到一个npm的package里面，如果用钩子函数就没法实现这个。

**Comment by liuhe1989** [comment]
@vincent178  我接触node没多久，看到loon很喜欢，新项目想在生产环境试试，不知道有没有相对完备的文档，或者demo参考 loon中有很多特性及其使用场景在现有文档中并不完善。。。 很多东西看着大概知道是什么却无从下手。希望能得到指点！

**Comment by vincent178** [comment]
现有文档已经列出来了主要的功能，你可以从Controller入手，当express来用，能很快的建立一个api的服务，根据需求再添加数据库的支持。

我可以写一个简单的项目给你看一下。https://github.com/loon-project/loon-boilerplate

**Comment by vincent178** [comment]
```
$ git clone https://github.com/loon-project/loon-boilerplate
$ cd loon-boilerplate
$ npm i
$ npm run dev
```

**Comment by liuhe1989** [comment]
这个我都有看过 等遇到具体问题的时候再交流... TKS!!!
