### ISSUE TITLE
Service中无法使用外部公共模块

### ISSUE THREAD

**Issue by liuhe1989** [loon-project/loon#20]
![image](https://user-images.githubusercontent.com/18466417/33587716-5711fcaa-d9aa-11e7-9324-aefb99718d7a.png)
@vincent178 我将所有的业务代码全部注释掉依然没用 心态爆炸...

**Comment by liuhe1989** [comment]
@vincent178 service中使用的 async await 就会挂。。。
![image](https://user-images.githubusercontent.com/18466417/33588521-3ff1bf0c-d9ae-11e7-8434-4136b4ff4879.png)
我把此处代码全部注释掉就OK了。。。
但是我该怎么使用ES7语法呢

**Comment by liuhe1989** [comment]
定位带是依赖的外部模块后(使用的async await) 会引起此错误

**Comment by liuhe1989** [comment]
不行了 我还是先换主流框架了...

**Comment by vincent178** [comment]
才看到消息，明天早上我看一下

**Comment by vincent178** [comment]
请问下，你这个`upsertBarInfo`是个static方法吧，可能是因为static方法的原因
